import React from "react";
import styled from "styled-components";
import logo from '../../assets/images/logo.png';

const DoctorTreatment = () => {
  return (
    <div>
      <div className="mb-5" style={{ color: "#347571", textAlign: "center",marginTop:"2.5rem" }}>
        <h1>Doctor's Treatment</h1>
      </div>
      <div
        id="carouselExampleControls"
        className="carousel slide text-center carousel-dark"
        data-mdb-ride="carousel"
      >
        <div className="carousel-inner">
          <div className="carousel-item active">
            <div className="d-flex justify-content-center">
              <div
                className="py-4 rounded-4 col-md-4 col-12"
                style={{ backgroundColor: "#C1F9D3" }}
              >
                <img
                  className="py-3"
                  src={logo}
                  alt="avatar"
                  style={{ width: "300px" }}
                />
                <div className="row d-flex justify-content-center">
                  <div className="col-md-10 d-flex flex-column justify-content-center">
                    <h5 className="my-3">Patient Details</h5>
                    <div className="d-flex justify-content-center py-2">
                      <div className="text-start ms-md-0 ms-4">
                        <div className="fw-semibold">PID : 123</div>
                        <div>Patient Name : Name Of The Patient</div>
                        <div>Assigned Doctor : Name of Assigned Doctor</div>
                        <div>Department : Name of the Department</div>
                        <div>Token Generated by : Name of Receptionist</div>
                        <div>Token generated on Date: Current Date & Time</div>
                        <div>Room No : Room No of Assigned Doctor</div>
                        <div>Counter No : Number Of Counter</div>
                      </div>
                    </div>
                    <div className="py-3">
                      <h3>Token No: DEPID_DATE_09</h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="carousel-item">
            <div className="d-flex justify-content-center">
              <div
                className="py-4 rounded-4 col-md-4 col-12"
                style={{ backgroundColor: "#C1F9D3" }}
              >
                <img
                  className="py-3"
                  src={logo}
                  alt="avatar"
                  style={{ width: "300px" }}
                />
                <div className="row d-flex justify-content-center">
                  <div className="col-md-10 d-flex flex-column justify-content-center">
                    <h5 className="my-3">Patient Details</h5>
                    <div className="d-flex justify-content-center py-2">
                      <div className="text-start ms-md-0 ms-4">
                        <div className="fw-semibold">PID : 123</div>
                        <div>Patient Name : Name Of The Patient</div>
                        <div>Assigned Doctor : Name of Assigned Doctor</div>
                        <div>Department : Name of the Department</div>
                        <div>Token Generated by : Name of Receptionist</div>
                        <div>Token generated on Date: Current Date & Time</div>
                        <div>Room No : Room No of Assigned Doctor</div>
                        <div>Counter No : Number Of Counter</div>
                      </div>
                    </div>
                    <div className="py-3">
                      <h3>Token No: DEPID_DATE_09</h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="carousel-item">
            <div className="d-flex justify-content-center">
              <div
                className="py-4 rounded-4 col-md-4 col-12"
                style={{ backgroundColor: "#C1F9D3" }}
              >
                <img
                  className="py-3"
                  src={logo}
                  alt="avatar"
                  style={{ width: "300px" }}
                />
                <div className="row d-flex justify-content-center">
                  <div className="col-md-10 d-flex flex-column justify-content-center">
                    <h5 className="my-3">Patient Details</h5>
                    <div className="d-flex justify-content-center py-2">
                      <div className="text-start ms-md-0 ms-4">
                        <div className="fw-semibold">PID : 123</div>
                        <div>Patient Name : Name Of The Patient</div>
                        <div>Assigned Doctor : Name of Assigned Doctor</div>
                        <div>Department : Name of the Department</div>
                        <div>Token Generated by : Name of Receptionist</div>
                        <div>Token generated on Date: Current Date & Time</div>
                        <div>Room No : Room No of Assigned Doctor</div>
                        <div>Counter No : Number Of Counter</div>
                      </div>
                    </div>
                    <div className="py-3">
                      <h3>Token No: DEPID_DATE_09</h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <StyledLeftButton
          className="carousel-control-prev"
          role="button"
          data-bs-target="#carouselExampleControls"
          data-bs-slide="prev"
        >
          <span
            className="carousel-control-prev-icon"
            aria-hidden="true"
          ></span>
          <span className="visually-hidden">Previous</span>
        </StyledLeftButton>
        <StyledRightButton
          className="carousel-control-next"
          type="button"
          data-bs-target="#carouselExampleControls"
          data-bs-slide="next"
        >
          <span
            className="carousel-control-next-icon"
            aria-hidden="true"
          ></span>
          <span className="visually-hidden">Next</span>
        </StyledRightButton>
      </div>
    </div>
  );
};
export default DoctorTreatment;

const StyledLeftButton = styled.button`
  margin: -155px 0px 0px 0px;
`;

const StyledRightButton = styled.button`
  margin: -155px 0px 0px 0px;
`;