import React from 'react'
import jbplogoremove from '../../assets/images/jbplogoremove.png'
import Header from '../Header'

export default function Tokengenerated() {
  return (
    <div>
        <Header/>
        <div className='text-center w-100'>
        <h1 style={{color:"#347571"}}>Token Generated</h1>
        </div>
       <div className="d-flex justify-content-center mx-2 mt-4">
              <div
                className="py-4 rounded-4 col-md-4 col-12 text-center"
                style={{ backgroundColor: "#C1F9D3"}}
              >
                <img
                  className="py-3"
                  src={jbplogoremove}
                  alt="avatar"
                  style={{ width: "300px" }}
                />
                <div className="row d-flex justify-content-center">
                  <div className="col-md-10 d-flex flex-column justify-content-center">
                    <h5 className="my-3">Patient Details</h5>
                    <div className="d-flex justify-content-center py-2">
                      <div className="text-start ms-md-0 ms-4">
                        <div className="fw-semibold">PID : 123</div>
                        <div>Patient Name : Name Of The Patient</div>
                        <div>Assigned Doctor : Name of Assigned Doctor</div>
                        <div>Department : Name of the Department</div>
                        <div>Token Generated by : Name of Receptionist</div>
                        <div>Token generated on Date: Current Date & Time</div>
                        <div>Room No : Room No of Assigned Doctor</div>
                        <div>Counter No : Number Of Counter</div>
                      </div>
                    </div>
                    <div className="py-3">
                      <h3>Token No: DEPID_DATE_09</h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="container text-center mt-4">
            <div className='row text-center'>
               <div className="col-md-6 py-3"><button className='w-75 py-2 rounded-pill border-0 text-light fw-semibold' style={{backgroundColor:"#5ec57e"}}>Send Token as SMS</button></div>
               <div className="col-md-6 py-3"><button className='w-75 py-2 rounded-pill border-0 text-light fw-semibold' style={{backgroundColor:"#5ec57e"}}>Print the Token</button></div>
            </div>
            <div className='row text-center'>
               <div className="col-md-6 py-3 py-lg-0"><button className='w-75 py-2 rounded-pill border-0 text-light fw-semibold' style={{backgroundColor:"#5ec57e"}}>Go To Dashbord</button></div>
               <div className="col-md-6 py-3 py-lg-0"><button className='w-75 py-2 rounded-pill border-0 text-light fw-semibold' style={{backgroundColor:"#5ec57e"}}>Register An other Patient</button></div>
            </div>
            </div>
    </div>
  )
}